# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4709238553cefc79ba4286fd84cb3cf82e6127222d0e772ab1d3bbdf6d33de5ac647c76a10408f99fb02ba5ec2b4c6c82742bd34c531b943f4ff63abba4ed756

test:
  secret_key_base: af192cbc91fd1f4c1635ba9f557db87aa63628a11ee2eef76ed1aaa1a82a048bc0d27dbc6d86ef90f547b15807dee4fd5c928195db9ffde0f4b87d56610523a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
